Dev-ExerciseSetup
t4d-gmbh/Weekend-Out pull request #2
Opened 2024-09-23 08:01 UTC by matteodelucchi

Exercise instructions and a template `packing_list.md` file. Addressing [#10](https://github.com/t4d-gmbh/using-git-in-academia/issues/10)

2024-09-23 12:42 UTC, j-i-l approved these changes
:+1: I like it!

Suggestion:
We use the somewhat nerdy generic names: https://en.wikipedia.org/wiki/Alice_and_Bob, like Alice, Bob, Carol, Dan, ...

One thing I'm not certain about:
- Is this enough for the first session?

2024-09-24 07:13 UTC, matteodelucchi commented
> 👍 I like it!
> 
> Suggestion: We use the somewhat nerdy generic names: https://en.wikipedia.org/wiki/Alice_and_Bob, like Alice, Bob, Carol, Dan, ...
> 
> One thing I'm not certain about:
> 
> * Is this enough for the first session?

Great inputs! 
Regarding the work amount, I added some questions that should help the participants gain a deeper understanding of the basic git commands. We can discuss these in groups, answer them individually, or skip them if we're short on time. What do you think?

2024-09-24 21:52 UTC, j-i-l requested changes
I'll have another look tomorrow, was a long day today.

2024-09-24 21:52 UTC, j-i-l commented on README_solutions.md
> +Solution: If you try to push changes to a branch that has new commits on the remote repository, Git will reject the push and ask you to pull the changes first. This is because the remote branch has n
> and Git wants you to merge them before pushing your changes.

We can leave it as is, or write something like:

and Git wants you to first locally merge your changes and verify that the resulting state is healthy, before it is pushed to the remote. (Remember: The goal is to always keep a healthy reference)

2024-09-24 21:52 UTC, j-i-l commented on README_solutions.md
> +Solution: You can prevent a merge commit from being created when merging branches by using the `--no-ff` flag with the `git merge` command. This flag forces Git to create a merge commit even if it co
Hm...in case you meant to say: _"You can prevent a merge commit from being created when merging branches by using the ~`--no-ff`~ `--rebase` flag..._" I agree with you. :wink: 

- Avoid creating a merge commit: rebase instead of merge (see e.g. https://stackoverflow.com/a/30054231/1622937)
  so: `git pull --rebase`
- Always enforce a merge commit: add `--no-ff` option for `git pull/merge`.
  This is a bit trickier as 'pull/merge' can be done with `rebase` or with `--no-rebase` (i.e. `merge`). However the `--ff`/`-`-`--no-ff` only applie to the `merge` option which, by default, assumes `--ff` resolving a merge by simply fast-forwarding the branch pointer if possible, thus not creating any trace of an actual merge. To make sure that the history always shows a merge the `--no-ff` flag is needed.

One question might be to ask why one would always want to point out merge events even if a fast-forward would also be possible (solution: keep track of the feature branches in the feature branch approach)

2024-09-24 21:52 UTC, j-i-l commented on README_solutions.md
> +Solution: If you had merged the main branch into the `feature/blankets` branch instead, the changes from the main branch would have been applied to the `feature/blankets` branch. This would have incl
One thing that is crucial to point out here is that the resulting state would have been the same! (assuming no `ours/theirs` options were set in the merge - probably better just forget about that).
What is different: Which pointer is moved forward ('main' or 'feature/blankets') and (this too we might just better do not mention) the relative history, i.e. what commit you get when you write `<merge commit sha>^1`)
(another nice so answer: https://stackoverflow.com/a/12198219/1622937)

2024-09-24 21:52 UTC, j-i-l commented on README.md
> +- Which strategy would you had to use to merge the feature branch into the main branch without creating a merge conflict?
- `would you had` sounds unfamiliar to me. :sweat_smile:
- we might add: _Is avoiding a merge conflicts generally a good strategy?_ (solution: nope. Merge conflicts simply reflect a situation where resources were edited on distinct occasions within one update step of a branch. Such situations are bound to occur and trying to avoid them would go against the idea of having a distributed version control system. Avoiding them with `rebase` invents a history that looks as if the developers never concurrently worked on a same branch. If you value the "Logbook" character of a git history rebases are a no-no!

2024-09-24 21:52 UTC, j-i-l commented on README_solutions.md
> +git push origin feature/blankets
You will need the to set the upstream for a new local branch when you first push it:

`git push --set-upstream origin feature/blankets` or just `git push -u origin feature/blankets`

_note:_ Once the branch has a remote branch it tracks, you can simply use `git push`

2024-09-24 21:52 UTC, j-i-l commented on README_solutions.md
> +Solution: The default behavior of `git push` is to push the current branch to the remote repository. If you don't specify the branch name, Git will push the current branch to the remote repository.
This is true, but only once you have set the upstream branch name (i.e. the `-u` push).

2024-09-24 21:52 UTC, j-i-l commented on README_solutions.md
> +git pull origin main
`git pull origin main  or simply `git pull`

2024-09-30 07:49 UTC, matteodelucchi commented on README_solutions.md
> +git push origin feature/blankets
I think this situation will not occur in this exercise, because the repo has been cloned from a remote. Should we add a note to explain a situation where this could happen? IMHO, this could be regarded as "advanced" and does not need to be part of this introductory exercise. And also, Git usually tells you when to manually set the upstream (at least that's what I experienced).

2024-09-30 07:51 UTC, matteodelucchi commented on README_solutions.md
> +Solution: The default behavior of `git push` is to push the current branch to the remote repository. If you don't specify the branch name, Git will push the current branch to the remote repository.
see my comment above.

2024-09-30 07:58 UTC, matteodelucchi commented on README_solutions.md
> +Solution: The default behavior of `git push` is to push the current branch to the remote repository. If you don't specify the branch name, Git will push the current branch to the remote repository.
```suggestion
Solution: The default behavior of `git push` is to push the current branch to the remote repository. If you don't specify the branch name, Git will push the current branch to the remote repository. Think of a situation where you need to explicitly state the name of the remote and why this situation might be useful.
```

I am thinking of multiple remotes in case 
a) the repo is on a private/enterprise git server and also on a public GitHub or 
b) if a public repo has been cloned but you want the changes that you make not being public (forked public repos can't be made private) but still want to integrate the most recent changes from the public repo into your private one.

2024-09-30 08:58 UTC, matteodelucchi commented on README_solutions.md
> +Solution: You can prevent a merge commit from being created when merging branches by using the `--no-ff` flag with the `git merge` command. This flag forces Git to create a merge commit even if it co
Ok, this turns out to be more complex than I initially thought it would be ^^

```suggestion
Solution: By default, `git merge` performs a fast-forward merge if possible which is equal to `git merge --ff-only`. This means that if the branch being merged is directly ahead of the current branch, Git will simply move the branch pointer forward to the latest commit, avoiding the creation of a merge commit. For example, if your current branch is `main` and you want to merge `feature/blankets`: `git merge feature/blankets` if `main` can be fast-forwarded to include all commits from `feature/blankets`, Git will do so without creating a merge commit. If there are divergent commit on both branches, Git will create a merge commit to combine the histories. 
Non-default merge scenarios could be:
- *Merge with no fast-forward*: You want to ensure a merge commit is always created, even if a fast-forward merge is possible: `git merge --no-ff feature/blankets`. Git creates a merge commit to preserve the context of the feature branch. This can be useful for maintaining a clear project history, where each feature or bug fix is encapsulated in its own branch and merge commit, e.g., a merge commit clearly indicates that a feature or bug fix branch was integrated into the main branch. This helps in understanding the development history and the context of changes.
- *Rebase before merge*: Remember that `git pull` first fetches the lates changes from the remote with `git fetch` and then either calls `git merge` to fast-forward ahead of the current branch or rebases your current branch of top of those changes with `git merge --rebase`. You want to rebase your current branch on top of the branch you are merging from to maintain a linear history: `git pull --rebase origin main`
Note: Read the manuals of `git merge` and `git pull` to understand how different arguments affect each other.
```

2024-10-15 10:22 UTC, merged